### ISSUE TITLE
myLoadH5AD_Spatial

### ISSUE THREAD

**Issue by tlkennedy** [iaaka/visutils#1]
Hello,

I am struggling to use the function to load scanpy output into a seurat object.

Code is below;

seurat <- myLoadH5AD_Spatials("/Users/tlayton/Downloads/integration/adata_sct_final.h5ad")

Error in m$indptr : $ operator is invalid for atomic vectors

Any help would be appreciated!

**Comment by iaaka** [comment]
Hi @tlkennedy, thank you for reporting this, unfortunately there are no unified way to store visium data in anndata object, so I'm not really sure it is possible to write universal loader (however there are some attempts in SeuratDisk and [sceasy](https://github.com/cellgeni/sceasy). myLoadH5AD_Spatials function was designed to load h5ad containing multiple visium samples stored in specific way (chapter "Visium" of [this](https://github.com/cellgeni/c2l/blob/main/src/check-n-prepare.input.h5ad.ipynb) notebook gives an example on how to assemble anndata object that can be later loaded by  myLoadH5AD_Spatials. Probably changing library_id_field parameter may help. You can also try myLoadH5AD_Spatial function if your h5ad consist of just one sample.
If neither of above works, one can attempt to modify myLoadH5AD_Spatials to make it work with your object. I can look into this but I'll need access to your h5ad file.

**Comment by iaaka** [comment]
I'm closing the issue as the function was updated and moved to another [package](https://github.com/cellgeni/schard).
